# Generated by Django 3.1.5 on 2021-01-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('module', models.IntegerField()),
                ('notes', models.FileField(upload_to='pdfs')),
            ],
        ),
    ]
