# Generated by Django 3.1.5 on 2021-02-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_auto_20210130_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_pic',
            field=models.FileField(default='default.jpg', upload_to='profile_pic'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='Data Structures', max_length=50),
            preserve_default=False,
        ),
    ]
