# Generated by Django 3.1.5 on 2021-02-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_teacher_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='notes',
            new_name='notess',
        ),
    ]
